### ISSUE TITLE
Error downloading NaQ datasets

### ISSUE THREAD

**Issue by Davidyao99** [srama2512/NaQ#1]
Great Project!

I am trying to validate your model on the Ego4d NLQ v2 validation set. I am trying to download the NaQ datasets using the command `ego4d --output_directory="<OUTPUT DIRECTORY>" --datasets baselines/naq_datasets --version v2`. However, it showing a `botocore.exceptions.ClientError: An error occurred (403) when calling the HeadObject operation: Forbidden` error. Any idea why this is happening and how I can go about resolving this? 

I have the right aws profile and permission since I am able to download the annotations using the ego4d cli. Thank you!!

**Comment by srama2512** [comment]
@Davidyao99 - I'm working on fixing the ego4d api issue. I've shared a copy of the dataset with you over email.

**Comment by srama2512** [comment]
Fixed the issue. The download tag was incorrect. The command also explicitly mentions that an AWS key to access Ego4D is required to download the dataset.

**Comment by Umer03213842277** [comment]
> @Davidyao99 - I'm working on fixing the ego4d api issue. I've shared a copy of the dataset with you over email.

Could you please share a copy with me. I need it for my Final Year Project in university. Please share it at k200427@nu.edu.pk

Thanks alot.
