### ISSUE TITLE
Validating NaQ++

### ISSUE THREAD

**Issue by Davidyao99** [srama2512/NaQ#2]
I am trying to run the NaQ pretrained model on just the validation set of the NLQ challenge.

When running the inference command `bash ReLER/scripts/infer.sh 0 nlq_v2 test internvideo reler_internvideo_naq/video_tef-vlen600_internvideo/model_3448.t7`, I am receiving the following error:

`ValueError: data dir ./data/dataset/nlq_official_v2 does not exist`

I am not really sure what should be going into that directory. Looking at the code, it seems to contain train/val/test.json files? Where do I get these files to be placed in this directory?

**Comment by srama2512** [comment]
You can get `nlq_official_v2` by following the pre-processing steps [here](https://github.com/srama2512/NaQ#ego4d-nlq-2023-challenge). Note that `nlq_train_v2.json` and `nlq_val_v2.json` are the v2 release of the NLQ annotations.
