### ISSUE TITLE
NaQ++ Stage-1 pretrained checkpoint

### ISSUE THREAD

**Issue by xyzforever** [srama2512/NaQ#4]
Thank you for releasing the code of this excellent work! For EGO4D NLQ 2023 Challenge, I notice that only the finetuned NaQ++ model have been released. Will you release the checkpoint of the NaQ++ stage-1 pretrained model?

**Comment by srama2512** [comment]
Hi @xyzforever. No, we don't plan to release the stage-1 model since the NaQ++ release was largely to serve as baselines for the Ego4D challenge. You should be able to train the stage-1 model following our instructions [here](https://github.com/srama2512/NaQ#ego4d-nlq-2023-challenge).
