### ISSUE TITLE
Where is the code of temporal random jittering?

### ISSUE THREAD

**Issue by Becomebright** [srama2512/NaQ#6]
Hi, thanks for your impressive work. When studying your code, I can't find the implementation of TJR. Could you please help me point out its location? By the way, does the provided dataset include the jittering?

**Comment by srama2512** [comment]
@Becomebright - please check [here](https://github.com/srama2512/NaQ/blob/80a14a4f72eb8375bb926cfa79a90e638e93673c/VSLNet/utils/data_loader.py#L37-L39) for the TRJ function call. It is not a part of the provided dataset. The pytorch Dataset class will perform the jittering during training.
