### ISSUE TITLE
Repetition in Ego4D narrations

### ISSUE THREAD

**Issue by Christian-chen1206** [srama2512/NaQ#8]
Hello, thanks for your brilliant work. I want to know how you consider the problem of repeated narrations in Ego4D dataset, which means the same text will have different timestamps. We know the query text of NLQ may not duplicate. Do you just simply allow the existence of this case? Thanks.

**Comment by srama2512** [comment]
Hi, yes. That is possible. We didn't explicitly address this since we didn't want to throw away repeated narrations. A likely better way to handle this would be to treat this as a multi-instance localization task (similar to action detection).
